---
# provision EC2 and security group
- hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - ec2-sg-provisioning
    - ec2-provisioning

# Deploy go app on provisioned ec2
- hosts: ec2_launched
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - go-web

# add classic load baancer for port forwarding
- hosts: localhost
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - elb-provisioning
